name: CI

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.html'
      - '**/*.yaml'
      - '**/*.yml'
      - requirements*.txt
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.html'
      - '**/*.yaml'
      - '**/*.yml'
      - requirements*.txt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: make dev
      - name: Run pylint
        run: make lint
      - name: Run tests
        run: make test
